name: .NET Core CI

on:
  push:
    branches:
      - main  # or your main branch name
  pull_request:
    branches:
      - main  # or your main branch name

jobs:
  build:
    runs-on: windows-latest  # Specify Windows runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Adjust to the latest version that supports .NET 8.0

      - name: Set .NET SDK version
        run: dotnet --list-sdks  # Verify SDK version installed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Output message
        run: echo "Build and publish completed successfully."
