name: .NET Core CI

on:
  push:
    branches:
      - main  # adjust this to your main branch name if different
  pull_request:
    branches:
      - main  # adjust this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'  # adjust to the latest version that supports your target framework

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Output message
        run: echo "Build and publish completed successfully."
